[package]
name = "sui_moments"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Walrus = { git = "https://github.com/MystenLabs/walrus.git", subdir = "testnet-contracts/walrus", rev = "releases/walrus-v1.34.0-release" }

[addresses]
sui_moments = "0x0"